package models

import "time"

// TemperatureUnit defines the unit system for temperature values.
type TemperatureUnit string

const (
	UnitCelsius    TemperatureUnit = "celsius"
	UnitFahrenheit TemperatureUnit = "fahrenheit"
	UnitKelvin     TemperatureUnit = "kelvin"
)

// AlertSeverity defines the severity level of a weather alert.
type AlertSeverity string

const (
	SeverityLow     AlertSeverity = "low"
	SeverityMedium  AlertSeverity = "medium"
	SeverityHigh    AlertSeverity = "high"
	SeverityExtreme AlertSeverity = "extreme"
)

// Coordinates holds a geographic lat/lon pair.
type Coordinates struct {
	Lat float64 `json:"lat" binding:"required,min=-90,max=90"`
	Lon float64 `json:"lon" binding:"required,min=-180,max=180"`
}

// Location is a saved location with metadata.
type Location struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Coordinates Coordinates `json:"coordinates"`
	CreatedAt   time.Time   `json:"createdAt"`
}

// LocationCreate is the request body for POST /api/locations.
type LocationCreate struct {
	Name string  `json:"name" binding:"required,min=1,max=200"`
	Lat  float64 `json:"lat"  binding:"required,min=-90,max=90"`
	Lon  float64 `json:"lon"  binding:"required,min=-180,max=180"`
}

// LocationUpdate is the request body for PUT /api/locations/:id.
// All fields are optional — only provided (non-nil) fields are updated.
type LocationUpdate struct {
	Name *string  `json:"name" binding:"omitempty,min=1,max=200"`
	Lat  *float64 `json:"lat"  binding:"omitempty,min=-90,max=90"`
	Lon  *float64 `json:"lon"  binding:"omitempty,min=-180,max=180"`
}

// CurrentWeather holds the current weather data for a location.
type CurrentWeather struct {
	Temperature   float64         `json:"temperature"`
	FeelsLike     float64         `json:"feelsLike"`
	Humidity      float64         `json:"humidity"`
	Pressure      float64         `json:"pressure"`
	WindSpeed     float64         `json:"windSpeed"`
	WindDirection int             `json:"windDirection"`
	Description   string          `json:"description"`
	Icon          string          `json:"icon"`
	Timestamp     int64           `json:"timestamp"`
	LocationName  string          `json:"locationName"`
	Units         TemperatureUnit `json:"units"`
}

// ForecastDay holds aggregated weather data for a single day.
type ForecastDay struct {
	Date        string  `json:"date"`
	TempMin     float64 `json:"tempMin"`
	TempMax     float64 `json:"tempMax"`
	Humidity    float64 `json:"humidity"`
	Description string  `json:"description"`
	Icon        string  `json:"icon"`
}

// Forecast holds a multi-day weather forecast for a location.
type Forecast struct {
	LocationName string          `json:"locationName"`
	Units        TemperatureUnit `json:"units"`
	Days         []ForecastDay   `json:"days"`
}

// WeatherAlert is a threshold-based custom alert generated by the service.
type WeatherAlert struct {
	AlertType string        `json:"alertType"`
	Message   string        `json:"message"`
	Severity  AlertSeverity `json:"severity"`
	Value     float64       `json:"value"`
	Threshold float64       `json:"threshold"`
}

// WeatherQueryParams holds query parameters for weather endpoints.
type WeatherQueryParams struct {
	Lat   float64         `form:"lat"   binding:"required,min=-90,max=90"`
	Lon   float64         `form:"lon"   binding:"required,min=-180,max=180"`
	Units TemperatureUnit `form:"units"`
}

// ForecastQueryParams holds query parameters for the forecast endpoint.
type ForecastQueryParams struct {
	Lat   float64         `form:"lat"   binding:"required,min=-90,max=90"`
	Lon   float64         `form:"lon"   binding:"required,min=-180,max=180"`
	Days  int             `form:"days"  binding:"omitempty,min=1,max=5"`
	Units TemperatureUnit `form:"units"`
}

// AlertQueryParams holds query parameters for the alerts endpoint.
type AlertQueryParams struct {
	Lat float64 `form:"lat" binding:"required,min=-90,max=90"`
	Lon float64 `form:"lon" binding:"required,min=-180,max=180"`
}

// LocationWeatherQueryParams holds query parameters for GET /api/locations/:id/weather.
type LocationWeatherQueryParams struct {
	Units TemperatureUnit `form:"units"`
}

// OwmWeatherEntry is a single weather condition entry from the OWM API.
type OwmWeatherEntry struct {
	ID          int    `json:"id"`
	Main        string `json:"main"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

// OwmMain holds the main weather metrics from the OWM API.
type OwmMain struct {
	Temp      float64 `json:"temp"`
	FeelsLike float64 `json:"feels_like"`
	TempMin   float64 `json:"temp_min"`
	TempMax   float64 `json:"temp_max"`
	Pressure  float64 `json:"pressure"`
	Humidity  float64 `json:"humidity"`
}

// OwmWind holds wind data from the OWM API.
type OwmWind struct {
	Speed float64 `json:"speed"`
	Deg   int     `json:"deg"`
}

// OwmCurrentWeatherResponse is the parsed response from /data/2.5/weather.
type OwmCurrentWeatherResponse struct {
	Weather []OwmWeatherEntry `json:"weather"`
	Main    OwmMain           `json:"main"`
	Wind    OwmWind           `json:"wind"`
	Dt      int64             `json:"dt"`
	Name    string            `json:"name"`
}

// OwmForecastItem is a single 3-hour interval entry from /data/2.5/forecast.
type OwmForecastItem struct {
	Dt      int64             `json:"dt"`
	Main    OwmMain           `json:"main"`
	Weather []OwmWeatherEntry `json:"weather"`
	DtTxt   string            `json:"dt_txt"`
}

// OwmCity holds city metadata from the OWM forecast response.
type OwmCity struct {
	Name string `json:"name"`
}

// OwmForecastResponse is the parsed response from /data/2.5/forecast.
type OwmForecastResponse struct {
	List []OwmForecastItem `json:"list"`
	City OwmCity           `json:"city"`
}
